int _putchar(char c);
  2 void print_alphabet(void);
  3 void print_alphabet_x10(void);
  4 int _islower(int c);
  5 int _isalpha(int c);
  6 int print_sign(int n);
  7 int _abs(int n);
  8 int print_last_digit(int n);
  9 void jack_bauer(void);
 10 void times_table(void);
 11 int add(int a, int b);
 12 void print_to_98(int n);
 13 void print_times_table(int n);
